### ISSUE TITLE
Why isn't the class Function and LazyFunction static?

### ISSUE THREAD

**Issue by JarvisJin** [uklimaschewski/EvalEx#111]
due to the inner class  Function and LazyFunction is not static,  so if I have many expressions , and thay all use the same function named "pmt",  I need to  new the Function pmt  every time and cannot reuse the Function pmt object. 

btw,  the method and() with(), is there any difference between the two methods?

**Comment by uklimaschewski** [comment]
See issue #87 and the discussion there. Making them static woul break backward compatibility. I will probably go the the way I proposed there.
