### ISSUE TITLE
Comparision does not evaluate correctly with large numbers

### ISSUE THREAD

**Issue by gregorius90** [uklimaschewski/EvalEx#114]
`Expression expression = new Expression("timestamp >= 1500551315569");
System.out.println(expression.with("timestamp", "1500551315568").eval());`

Will print 1, but should print 0.
Tested with version 1.8 from maven central.

**Comment by uklimaschewski** [comment]
The default math context used in expressions has a precision of 7, which is too small for your numbers.
Either create the expression with a different math context, or specify the precision before evaluating:

````Java
Expression expression = new Expression("timestamp >= 1500551315569", new MathContext(13));
````
or
````Java
expression.with("timestamp", "1500551315568").setPrecision(13).eval();
````
