### ISSUE TITLE
Create precedence constants

### ISSUE THREAD

**Issue by gredler** [uklimaschewski/EvalEx#115]
Part of the public API for e.g. operators requires that you specify a precedence.

However, the precedence values for the built-in operators are all magic numbers hidden in the internals of the library.

As a result, there is no way to easily declare an operator as having a precedence equivalent to some well-known standard operator, or to easily declare it as higher or lower precedence than a built-in operator.

**Comment by uklimaschewski** [comment]
Thanks, good idea. I'll mark this as a feature request.

**Comment by uklimaschewski** [comment]
Implemented in version 1.18
