### ISSUE TITLE
Expression inside if-branch not evaluated lazy

### ISSUE THREAD

**Issue by nico72** [uklimaschewski/EvalEx#120]
`if(a=0,0,abs(12/a))` (with a = 0) causes a `java.lang.ArithmeticException: Division by zero`, because `abs(12/a)` isn't evaluated lazy.

When I change Function.lazyEval() to be really lazy the test succeeds.

https://github.com/nico72/EvalEx/commit/ada3c3d65e7c7512ec20ec46fde6ad034ce449b6

**Comment by uklimaschewski** [comment]
Thanks alot. Your solution looks ok from what I see. Can you create a pull request, so that I can merge the changes?
