### ISSUE TITLE
Implicit Multiplication with parentheses

### ISSUE THREAD

**Issue by Sxtanna** [uklimaschewski/EvalEx#123]
The simple expression `2(12)` fails with the exception 

```
Exception in thread "main" 
com.udojava.evalex.Expression$ExpressionException: Missing operator at character position 2
    at com.udojava.evalex.Expression.shuntingYard(Expression.java:1375)
    at com.udojava.evalex.Expression.getRPN(Expression.java:1746)
    at com.udojava.evalex.Expression.eval(Expression.java:1436)
```

I can understand the issue presented with this in #64 , but would it still be an issue if it was only strictly supported for expressions with parentheses?

For example:
`2(12)` = `(2 * 12)`
`10 + 4(21)` = `10 + (4 * 21)`
`12(2 - 20) - (-2)^3` = `12 * (2 - 20) - (-2)^3`

**Comment by uklimaschewski** [comment]
I marked this as an enhancement request. Should be possible and has been requested quite a few times.

**Comment by uklimaschewski** [comment]
I added this feature in Relase 1.13. See commit 88cf62e2ffedb8e1afcd6c5f7a6eff45755c3d07

**Comment by Sxtanna** [comment]
Thank you!
