### ISSUE TITLE
Add the ability to turn on/off stripTrailingZeros() from eval()

### ISSUE THREAD

**Issue by ryan-lg** [uklimaschewski/EvalEx#124]
The return of the eval method calls stripTrailingZeros() on the final result of the evaluation (if the result is not null). There are scenarios where one might not want to modify the result returned from EvalEx in order to get those trailing zeros added back in. 

Would it be possible to add the ability to "turn on/off" the stripTrailingZeros() in the return so one could control whether the result of eval either has the trailing zeros removed or not?

**Comment by uklimaschewski** [comment]
Yes, should be no problem. I put this on the enhancement list.

**Comment by uklimaschewski** [comment]
I have added it in Release 1.13. See commit 1d2ec46c022ab7da01bb7864000b4c5893dfbb60
The `eval()` function now has an optional parameter `stripTrailingZeros`. Default is `true`.
To strip the zeroes call `expression.eval(false)`.

**Comment by tviegut** [comment]
Thanks!

**Comment by ryan-lg** [comment]
Thank you for adding this in so quickly! 

One minor thing I noticed, shouldn't the return comment of the eval() method say that the trailing zeros are stripped instead of are not stripped?
