### ISSUE TITLE
Duplicate Maven POM plugin entries, and invalid element? etc..

### ISSUE THREAD

**Issue by Sxtanna** [uklimaschewski/EvalEx#127]
I forked the repo and opened it in IntelliJ, and there are duplicate plugins
- Maven JavaDoc Plugin
- Maven Source Plugin

![image](https://user-images.githubusercontent.com/20979389/30551514-afaaa936-9c68-11e7-8b12-69116ea444d5.png)

Is there any reason these are listed twice?

Also there is an error in the POM under the Nexus Staging Maven Plugin
![image](https://user-images.githubusercontent.com/20979389/30551310-187e7150-9c68-11e7-9ede-0ee46809e792.png)

I have made no modifications to anything in this project, simply imported it.

And 1 last issue I see is the lack of specific formatting in the POM? Would it be ok if I added proper spacing in between the blocks to make it more readable?

The project doesn't specify target version and this causes IntelliJ  to assume 1.5, this language level clashes with certain language features you use such as

![image](https://user-images.githubusercontent.com/20979389/30551457-7c1ec778-9c68-11e7-85cf-7c8a30133f75.png)

and 

![image](https://user-images.githubusercontent.com/20979389/30551467-861e3ba0-9c68-11e7-8a81-912c7b44626d.png)

**Comment by uklimaschewski** [comment]
I am not using maven for development, I use this pom mainly for creating and uploading the required artifacts for maven central through Sonatype. I could try to run this with your requested fixes and see what will happen.

**Comment by Sxtanna** [comment]
I've made what I believe to be necessary changes to the pom in this gist. @uklimaschewski 
[POM Gist](https://gist.github.com/Sxtanna/358f17f50bf1cafcc44ee97979281def)

**Comment by uklimaschewski** [comment]
Thanks @Sxtanna, I will try it out this weekend, if I find some time.

**Comment by Sxtanna** [comment]
Ok thank you, looking forward to it. @uklimaschewski

**Comment by uklimaschewski** [comment]
@Sxtanna
I have tested your new pom.xml and it worked without error.
Though there is one problem with it: Only the javacode jar was uploaded to Sonatype and Maven central for version 1.14.
The javadoc and sources jars are missing. Possibly that is the reason why they were twice in the pom.
You can see the result at Maven central:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.udojava%22%20AND%20a%3A%22EvalEx%22

And the log of the build process is here:
http://www.rultor.com/t/13000-1

**Comment by Sxtanna** [comment]
Addressed in #129 and resolved in #131
