### ISSUE TITLE
Support for customized functions with return of string and another types

### ISSUE THREAD

**Issue by sirlordt** [uklimaschewski/EvalEx#133]
Hello excellent parser but lack of functions of String, LocalDateTime, maybe better support of override o create customized functions with return of specific types not only LazyNumber.

**Comment by uklimaschewski** [comment]
There is a limited string support, see the readme. But this library is mainly meant for numerical epressions.

**Comment by RobertZenz** [comment]
@sirlordt Converting the date/time to a Unix timestamp would make it possible to be processed. I mean, that would involve quite some "preprocessing" if you allow to enter the equation, but should be rather straight forward.

**Comment by uklimaschewski** [comment]
I'll close this until somebody comes up with a good solution for general string support
