### ISSUE TITLE
Results are rounded

### ISSUE THREAD

**Issue by iAreas** [uklimaschewski/EvalEx#136]
I'm trying to evaluate ``856 * 288 * 549 * 995`` with 
```java
BigDecimal result = new Expression("856 * 288 * 549 * 995").eval()
```
and display the result with 
```java
System.out.println(result.toPlainString());
```
But instead of getting ``134667152649`` (which is the correct result), I get ``134667200000``.
Is there a way to prevent such rounding? Please let me know.

Thanks in advance!

**Comment by squeek502** [comment]
See the [BigDecimal docs](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html) and the [MathContext docs](https://docs.oracle.com/javase/7/docs/api/java/math/MathContext.html). 

EvalEx uses a default of `MathContext.DECIMAL32`. You can change that either in your Expression constructor (`new Expression("856 * 288 * 549 * 995", MathContext.DECIMAL128)`) or afterwards (`expression.setPrecision(34)`)

**Comment by iAreas** [comment]
Thanks, you solved it!!
