### ISSUE TITLE
Boolean evaluation is broken

### ISSUE THREAD

**Issue by dendolder** [uklimaschewski/EvalEx#139]
new Expression("0 && 0").eval() returns 0 -> correct
new Expression("0.0 && 0.0").eval() returns 1 -> incorrect

Reason is that the eval() function of the &&-operator. should use the compareTo() function of BigDecimal , not the equals() function. Same problem exists for the ||-operator and IF.

**Comment by RobertZenz** [comment]
To add some details, the `compareTo` method does ignore the scale of the `BigDecimal`, while `equals` does also compare the scale of the two `BigDecimal`s indifferent of if there are "enough" decimal places or not.

**Comment by uklimaschewski** [comment]
Thanks, I'll have a detailed look at it

**Comment by uklimaschewski** [comment]
I hope I fixed it. See version 1.18.
