### ISSUE TITLE
Out Of Order Embedded Variables

### ISSUE THREAD

**Issue by nictomlinson** [uklimaschewski/EvalEx#142]
I have a proposed change to handle issues related to inter-dependant and out of order variables.

[src.zip](https://github.com/uklimaschewski/EvalEx/files/1549560/src.zip)
With the current code using word substitutions, it is necessary to add (.with, .and) variables in order. With this change, variables are treated as LazyNumbers rather than being substituted (c.f functions and variables of type number) and are then evaluated on demand. There are performance improvements that can be had here such as keeping tracked of evaluated variables to avoid re-evaluation but that needs more work as it requires to differentiate between non-volatile and volatile variables (e.g. if a variable depends on a function that returns a random number).
I have attached a zip of the modified src as I wasn't able to create a pull request.
What are your thoughts on this change?

**Comment by squeek502** [comment]
Could you provide an example of what you mean? By 'in order', are you saying that the following doesn't currently work right?

```java
new Expression("x+y").with("y", "1").and("x", "2").eval();
```

**Comment by uklimaschewski** [comment]
For me, it's also not clear what you want to achieve. Can you give an example?
Please try to submit a pull request, as this makes alot of things (e.g. compare  and test) much easier.
Here's how to create one: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by nictomlinson** [comment]
Given an expression and a set of defined variables, you need to analyse the expression and those variables in order to determine the substitution order or you need to repeatedly substitute until all variables that remain in the expression are defined as numbers.

Consider:

e = new Expression("x+y")
e.with("x","a+1") // e is now "a+1+y"
e.with("y","x+a") // e is now "a+1+x"
e.with("a",2) // e is now "2+1+x"

This will not evaluate as we still have an "x" to substitute.

Had we analysed the expression and all the variables first we could have worked out an order for the variable definitions which worked such as:

e = new Expression("x+y")
e.with("y","x+a") // e is now "x+x+a"
e.with("x","a+1") // e is now "a+1+a+1+a"
e.with("a",2) // e is now "2+1+2+1+2"

and this does evaluate.

In some cases, this analysis would become complex. Also, i'm not sure if you can always define an order such that each variable only needs to be specified once.

What I'm trying to achieve is that the order of providing the variable definitions to the expression does not affect the outcome of the evaluation providing all variables are provided.

I'll try to do the pull request later.

**Comment by nictomlinson** [comment]
Discussion on this enhancement can continue on the pull request [here](https://github.com/uklimaschewski/EvalEx/pull/143#issue-281548131)
