### ISSUE TITLE
Why is Function an instance inner class of Expression?

### ISSUE THREAD

**Issue by RobertZenz** [uklimaschewski/EvalEx#144]
In my project, which uses EvalEx, I had to implement a custom `Function` and the requirement that the `Function` is an instance-inner-class struck me as quite odd. I did not look through the whole source code to be honest, but is it a requirement that the `Function`s have access to the enclosing `Expression` instance? Could they be made `static` instead?

Example, if I want to add a new `Function` I have to extend the `Expression` first:

    public class ExtendedExpression extends Expression {
        // Constructors as needed.
        public class BestFunction extends Function {
            // Class body
        }
    }
    
    // Usage
    ExtendedExpression expression = new ExtendedExpression("best(1, 2, 3)");
    expression.addFunction(expression.new BestFunction());

Which makes it rather hard to quickly add custom functions.

**Comment by uklimaschewski** [comment]
This is for backwards compatibility. See discussion in issue #87.
I will probably go into the direction, I pointed out there. I experimentally tested in the 'externalize' branch.
(See source at: https://github.com/uklimaschewski/EvalEx/tree/Externalize/src/com/udojava/evalex)

**Comment by RobertZenz** [comment]
I see.

Some feedback on that branch:

 * I wouldn't name the method `addExternal*`, but instead overload `addFunction` to accept the new `Function`.
 * Also I'd take the opportunity and make `Function` an interface with an abstract default implementation. That would allow other objects to implement it if they already extend another class, which would make the whole thing more flexible.
 * Just as a note, Java conventions state that `abstract` classes are prefixed with `Abstract` in their name to make that more clear.
 * I wouldn't use the `External` prefix, though it might be confusing having the internal and "external" classes with the same name, I believe it would make a cleaner API.

**Comment by RobertZenz** [comment]
And giving it some more thought, the internal classes then could directly extend the external classes, that would minimize complexity greatly. Thinking this further, that might also eliminate the need for an additional `addFunction`...but need to think about this some more.

**Comment by uklimaschewski** [comment]
Thanks for the input. I'll consider your ideas. Maybe I will find some time after christmas to give it a try.

**Comment by RobertZenz** [comment]
I'd like to work on this if you don't mind. Though, I will also only find the time for it after the holidays.

Are there unit tests in place which test the backwards compatibility (for the clients you mentioned) or need these to be created?

**Comment by uklimaschewski** [comment]
OK, thanks alot. If the current tests run without modifying them, then this proves enough backward and binary compatibility, I hope. Watch out when changing public/protected method signatures, though.

**Comment by RobertZenz** [comment]
I'm asking because if I change the `addFunction` method signature (by using the "new external" class) it will be source compatible, but not binary compatible. That is the only "breakage" that I currently see happening.

**Comment by uklimaschewski** [comment]
If you think, you can do this without changing the existing test code, go ahead.
We can set the version to 2.0, to show that there is a binary incompatibility to earlier version.

**Comment by RobertZenz** [comment]
I've started working on this, you can see the "preview" of the changes in my [refactoring branch](https://github.com/RobertZenz/EvalEx/tree/refactoring).

The most important things to note:

 * Two new interfaces: `Function` and `LazyFunction`
 * Two new abstract classes: `AbstracFunction` and `AbstractLazyFunction`
 * I had to fully classify the new interfaces in `Expression`, that is unfortunate but there is no other way I'm afraid (because of the name clashes between `LazyFunction` and `Expression.LazyFunction`.
 * I've duplicated some of the tests which are using the abstract classes.
 * I'd need to extract the helper functions like `assertNotNull(BigDecimal)` somewhere else so that they can be reused. Most likely into `AbstractLazyFunction`.

The new class hierarchy looks like this:

    interface LazyFunction
    interface Function extends LazyFunction
    
    class AbstractLazyFunction implements LazyFunction
    class AbstractFunction extends AbstractLazyFunction implements LazyFunction

Comments are obviously welcome, note that this is a preview so Javadoc and some cleanup is still missing. The tests are working and the changes inside `Expression` are minimal.

I've been thinking about convenience factory methods, something like this (with Java 8):

    expression.addFunction(AbstractFunction.oneArg("NAME", (parameters) -> {
        return parameters.get(0).multiply(new BigDecimal("8"));
    });

But that does not do much, now that I think about it and see it.

**Comment by RobertZenz** [comment]
@uklimaschewski I've been just putting more work into it and I noticed that `Expression` and `Operator` are immutable, with the exception of the boolean operator flag. Was that intended?

**Comment by RobertZenz** [comment]
Could you please review my changes? I'm not sure if that is something that you want.

 * New interfaces
   * `LazyFunction`
   * `Function`
   * `Operator`
 * New abstract classes
   * `AbstractLazyFunction`
   * `AbstractFunction`,
   * `AbstractOperator`
   * `AbstractUnaryOperator`

Otherwise the changes list from the previous comment applies.

**Comment by uklimaschewski** [comment]
@RobertZenz I'll have a look tomorrow.

**Comment by uklimaschewski** [comment]
@RobertZenz That looks great! All the original tests run without modification and the name clashes betweeen the internal and external interfaces is ok. I think your solution is quite elegant, keeping backwards compatibility and giving the possibility to define functions/operators also externally.
If you feel ready, you can issue a pull request. I'll be happy to merge it to the main trunk.

**Comment by RobertZenz** [comment]
I've created the pull request #149.

Before I forget again, I've removed the `setBooleanFunction` along the way because it didn't make much sense that it was there (also because I forgot about it when I copied stuff around). If I should add it back just drop me a note.
