### ISSUE TITLE
Small performance improvement

### ISSUE THREAD

**Issue by gee-age** [uklimaschewski/EvalEx#145]
Hi & thx, great parser!
Would it be possible to add a method like this?
```java
/**
   * Returns the used variable names by triggering the creation of the internal <b>cached</b> RPN.<br>
   * This method may takes more time than {@link #getUsedVariables()}  but it improves the performance
   * of a later {@link #eval()} call.
   * @return the used variable names
   */
  public Set<String> getVariables(){
    return getRPN().stream()
        .filter(t -> t.type == TokenType.VARIABLE)
        .map(t -> t.surface)
        .collect(java.util.stream.Collectors.toSet());
  }
```
In my typical scenario I did not know the variables inside the expression so I have to call 
method **Expression#getUsedVariables()** before **#eval()** always. Both methods will parse the tokens.
With the new method I get a performance improvement of about 10% ;)

Thx&Best Regards
gee

**Comment by uklimaschewski** [comment]
Thanks, would be possible.
You can fork and create a pull request, which I can merge.
Some notes:
- I would like to have this Java-6 compatible for now. So no streams, please.
- ```getUsedVariables()``` filters out teh constants (PI, TRUE, FALSE, E), I think this one should do this, too.
- Naming the method ```getVariableFromRPN()``` makes it clearer, even without reading the doc.
- The existing ```getUsedVariables()``` returns a List, this one should do this, too.
- Add at least one unit test

**Comment by uklimaschewski** [comment]
I'm closing this for now, as there was no feedback.
