### ISSUE TITLE
There are parameters like P114, P115 ...

### ISSUE THREAD

**Issue by sebahattinkoc** [uklimaschewski/EvalEx#148]
Expression e = new Expression("P114=\"ABC125\"");
        e.addLazyFunction(e.new LazyFunction("P114", -1) {

            private Expression.LazyNumber ZERO = new Expression.LazyNumber() {
                public BigDecimal eval() {
                    return BigDecimal.ZERO;
                }
                public String getString() {
                    return "0";
                }
            };

            private Expression.LazyNumber ONE = new Expression.LazyNumber() {
                public BigDecimal eval() {
                    return BigDecimal.ONE;
                }
                public String getString() {
                    return null;
                }
            };
            
            @Override
            public Expression.LazyNumber lazyEval(List<Expression.LazyNumber> lazyParams) {

                String tmpParemetre = "";
                String parametreName = lazyParams.get(0).getString();
                String valueName = lazyParams.get(1).getString();

                if (parametreName.equals("P114"))
                    tmpParemetre = "ABC125";

                if (tmpParemetre.equals(valueName))
                    return ZERO;
                else
                    return ONE;
            }
        });

**Comment by RobertZenz** [comment]
Wait a moment, that code doesn't make much sense. What are you trying to do?

**Comment by sebahattinkoc** [comment]
String tmp = "P114=\"AB52\" & P115=\"A\" ";

P114  = Customer code, P115 Customer Payment Code, P116, P117  ...

for example
P114 = "AB52" 
P115 = "5"

boolean t = false;
if ("AB52"=="AB52" && "5"=="A")
    t=true;

String tmp = "P114=\"10A\" & P115=\"GBH\" ";

for example
P114 = "10A" 
P115 = "ADCD"

boolean t = false;
if ("10A"=="10A" && "5"=="GBH")
    t=true;

**Comment by sebahattinkoc** [comment]
P114="ABC125" _**convert**_ P114(\"ABC125\")  it is solved this way. 

**_I want to use it without converting._**

        Expression e = new Expression("P114(\"ABC125\")");
        e.addLazyFunction(e.new LazyFunction("P114", -1) {

            @Override
            public Expression.LazyNumber lazyEval(List<Expression.LazyNumber> lazyParams) {

                String parametreValue = lazyParams.get(0).getString();
                String valueName = "ABC125";

                if (parametreValue.equals(valueName))
                    return new Expression.LazyNumber() {
                        public BigDecimal eval() {
                            return BigDecimal.ZERO;
                        }
                        public String getString() {
                            return "0";
                        }
                    };
                else
                    return new Expression.LazyNumber() {
                    public BigDecimal eval() {
                        return BigDecimal.ONE;
                    }
                    public String getString() {
                        return null;
                    }
                };
            }

        });

**Comment by RobertZenz** [comment]
I don't think there is String support at all in EvalEx...

**Comment by uklimaschewski** [comment]
There is support for Strings literals in EvalEx, but only in function parameters.
I think, I understand your problem. But a more general support for string values would require to also support variables to be string literals.
I did some tests, but this seems to be a bit tricky to implement.
Maybe this is a thing for the future, though EvalEx was never designed to support strings.
I'll mark this as an enhancement, but do not promise anything. ;-)

**Comment by sebahattinkoc** [comment]
Thank you so much. I will wait for your solution.

**Comment by uklimaschewski** [comment]
I'll close this until somebody comes up with a good solution for general string support
