### ISSUE TITLE
bit operation with long integer

### ISSUE THREAD

**Issue by edoroe** [uklimaschewski/EvalEx#151]
Hi, Udo !
Please add bit operation ( &, |, ^, !) with integer value.
Thank !

**Comment by notmmao** [comment]
My solution:  Custom Operator
```java
public BigDecimal myEval(String expressionString) {   
	Expression ex = new Expression(expressionString);
	ex.addOperator(ex.new Operator("&", 30, true) {
		@Override
		public BigDecimal eval(BigDecimal v1, BigDecimal v2) {
			int v = v1.intValue() & v2.intValue();
			return new BigDecimal(v);
		}
	});
	return ex.eval();
}
```

**Comment by RobertZenz** [comment]
@notmmao You might be losing precision here, though. Converting them to a `BigInteger` first and then using [the shift functions](https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html#shiftRight-int-) should be a "good enough" implementation.

**Comment by uklimaschewski** [comment]
Closing this for now, as it seems not to have too much attention
