### ISSUE TITLE
Problems with adding an unary operator

### ISSUE THREAD

**Issue by TotemGuo** [uklimaschewski/EvalEx#152]
I've found a problem when adding an unary operator '~' to an Expression.

exp.addOperator(new AbstractUnaryOperator("~",60,false) {
            @Override
            public BigDecimal evalUnary(BigDecimal bigDecimal) {
                return bigDecimal;
            }
});

unknown unary operator  '~' occured.

Did anyone have this problem?

**Comment by uklimaschewski** [comment]
@TotemGuo:  A bit late answer, but I fixed this in commit e5c164680b0b15e838b4dd5f338fec4b0d32fedb
