### ISSUE TITLE
Add LazyOperator the same way that there is LazyFunction

### ISSUE THREAD

**Issue by RoiSoleil** [uklimaschewski/EvalEx#153]
Add LazyOperator the same way that there is LazyFunction

**Comment by uklimaschewski** [comment]
@RoiSoleil Can you give an example of what you want to achieve with a "lazy" operator?

**Comment by RoiSoleil** [comment]
To achieve the same thing that with LazyFunction, be able to manipulate "String" value in Operator.
My final goal is to create a LazyNumberWrapper that implements LazyNumber, this class will be a wrapper to "business" object. To do so i need that all the evaluation process manipulate LazyNumber and not only BigNumber.

**Comment by RobertZenz** [comment]
Mh, do you mean that `Operator` interface should define the function `eval(LazyNumber v1, LazyNumber v2)`?

**Comment by RoiSoleil** [comment]
Yes the && operator should be lazy if the first operand is false we don't have to evaluate the second one for example.

**Comment by RobertZenz** [comment]
I see, good idea.

**Comment by uklimaschewski** [comment]
I'll mark this as an enahancement

**Comment by RoiSoleil** [comment]
Ok thx.

**Comment by RobertZenz** [comment]
@uklimaschewski I've finished the changes, when you've got the time please review them. I've added a few short questions to the description of things which I'm unsure about.

**Comment by uklimaschewski** [comment]
@RoiSoleil can we close this now with the changes by @RobertZenz ?
BTW.: Thanks for the enhancement, Robert. :-)
