### ISSUE TITLE
Rounding results

### ISSUE THREAD

**Issue by daniela201841** [uklimaschewski/EvalEx#162]
Hi, I'm using EvalEx to evaluate big expressions.
For example: (((((1+(((1+6.39000000/100)^(1/252)-1)*3000)/3000)*(1+0.00000000/100)^(1/30))  -1)* (1+ 0.000000 / 100))+ 1) * 384499245.43570000

It returns: 384593800.0000000000
I want that be returned the exactly value: 384593766.66360000

Do you have some sugestion? Thanks.

**Comment by RobertZenz** [comment]
The default `MathContext` does not have such precision, you want to set the precision or a different `MathContext` for this case.

See #114 and #136.

**Comment by daniela201841** [comment]
Thank you very much!!!
