### ISSUE TITLE
Is there a setting to understand trigonometric functions in Radians?

### ISSUE THREAD

**Issue by ayanovsk** [uklimaschewski/EvalEx#164]
Is there a setting to understand trigonometric functions in Radians?

Suppose we offer to the user to input the function. I'd think that a lot of math informed users would expect that sin(x) will take argument in Radians, and a special explanation would be necessary for users to enter sin(DEG(x)) instead of sin(x).

**Comment by RobertZenz** [comment]
You can always override the built-in functions with your own, so you can attach a new `sin` function by simply putting it into the expression with `addFunction(...)`.

**Comment by ayanovsk** [comment]
Thanks a lot.
Will try to do it.
