### ISSUE TITLE
Wrong sum

### ISSUE THREAD

**Issue by hogmuzzle80** [uklimaschewski/EvalEx#172]
formula: 9516923+6224+321760+121474+0+225206+1870093+140362+14094
return: 12216130
must return 12216136

**Comment by RobertZenz** [comment]
Duplicate of #114.

**Comment by hogmuzzle80** [comment]
And I know the reason. 
addOperator(new Operator("+", OPERATOR_PRECEDENCE_ADDITIVE, true) {
			@Override
			public BigDecimal eval(BigDecimal v1, BigDecimal v2) {
				assertNotNull(v1, v2);
				return v1.add(v2, **mc**);
			}
		});
MathContext is used and values are rounded according to the MathContext settings.
