### ISSUE TITLE
validate() error

### ISSUE THREAD

**Issue by sunzhiran** [uklimaschewski/EvalEx#175]
expression = new Expression("1 1+2/"); the result is 1.5;but this expression is not legal

**Comment by RobertZenz** [comment]
EvalEx does support [Reverse Polish Notation](https://en.wikipedia.org/wiki/Reverse_Polish_notation), I'm not completely sure but that might actually be a valid expression. For example, `1 + (1 2)/` is also a valid expression.

But I have too little experience with RPN and the parser of EvalEx to be completely sure about that.

**Comment by uklimaschewski** [comment]
I added a syntax check for this to the shunting yard method.
EvalEx works with RPN internally when an expression is evaluated.
For this, it uses a shunting yard algorithm to transform a normal expression to RPN notation.
But the above expression is not even a RPN.
