### ISSUE TITLE
Percentage operator

### ISSUE THREAD

**Issue by vanniktech** [uklimaschewski/EvalEx#180]
I'd like to have a percentage operator. Initially, I thought of using `%` but seems like this library is already reserving it for modulo.

Some example input and what I'd expect.

```
5% = 0.05
5%x5 = 0.25
500% = 5
500%10 = 50
51%6.75=3.4425
```

Maybe a dedicated function `perc` could help here since `%` is already taken.

**Comment by danielpeintner** [comment]
out of curiosity (and also need)... @vanniktech did you look into the internals of EvalEx to check whether it might be possible to implement the percentage operator.

I am aware of modulo and the possible conflicts but to my understanding it would be ideal to allow both "2 % 3" as modulo expression and "20%" to match peoples expectation.

**Comment by RobertZenz** [comment]
If I recall correctly, for the parser it does not matter whether it is unary or normal operator. So this would conflict for sure.

**Comment by uklimaschewski** [comment]
Fixed with #257
