### ISSUE TITLE
API inconsistency regarding Token.

### ISSUE THREAD

**Issue by RobertZenz** [uklimaschewski/EvalEx#182]
`Expression` has the public method `getExpressionTokenizer()` which returns an `Iterator<Token>`. `Token` however is not public but package-private.

**Comment by barfoo4711** [comment]
I'd also like to have Token in the public or at least package protected api. Is there a reason to not do this?
Our business requirement is the possibility to replace the (technical) variable names in an expression with their meaningful and translated business values.

**Comment by RobertZenz** [comment]
This is fixed in [2.5](https://github.com/uklimaschewski/EvalEx/releases/tag/2.5).
