### ISSUE TITLE
is there a way to change Expression

### ISSUE THREAD

**Issue by kim24** [uklimaschewski/EvalEx#186]
Is there a way to change expression instead of creating a new Expression object each time especially I need to add custom operator before evaluating expression.

**Comment by RobertZenz** [comment]
No, but you can always write a factory method which does all the basic setup of the `Expression`.

I believe it would be rather easy to add, but as far as I know there isn't a way to remove a variable/function once added to the `Expression`, so being able to  set a different expression does only make partially sense.

**Comment by kim24** [comment]
This is an example of using Factory Pattern to generate expression that have our own custom operations.
The following code in kotlin, you can find any java equivalent easily.
```
class ExpressionFactory {
    companion object {
        fun createWith(
            expression: String,
            mathContext: MathContext = MathContext(128,RoundingMode.HALF_UP)
        ): Expression {
        val expressionEvaluator =  Expression(expression.toText(), mathContext)
        // Add all custom operations / Functions
        return expressionEvaluator
        }
    }
}
```
