### ISSUE TITLE
Can't eval big numbers

### ISSUE THREAD

**Issue by kim24** [uklimaschewski/EvalEx#187]
When I enter big numbers to get evaluated for example : 
`1111111111111111111111111111111111+1`
the evaluator gets blocked and don't evaluate expression.

**Comment by RobertZenz** [comment]
Possible duplicate of #114?

**Comment by kim24** [comment]
I checked the issue before posting I'm using big precision (128)  : 
```
class ExpressionFactory {
    companion object {
        fun createWith(
            expression: String,
            mathContext: MathContext = MathContext(128,RoundingMode.UNNECESSARY)
        ): Expression {
            return Expression(expression.toText(), mathContext).addCustomOperations(mathContext)
        }
    }
}
```

**Comment by RobertZenz** [comment]
I see. I can't check right now, but could you set the rounding mode to something different, like `HALF_UP`. And if that changes nothing, what are you doing in `addCustomOperations`?

**Comment by kim24** [comment]
I discovered the problem. the expression I give to eval is converted from Latex to text seems like the function I use for conversion is the reason why I have this problem.

**Comment by RobertZenz** [comment]
What kind of pipeline do you have over there? Are you solving equations inside Latex documents?

Also you can close this issue on your own, if you're not familiar with that.

**Comment by kim24** [comment]
I'm currently building a calculator.
the expression I have is fully latex so I need to convert it to normal expression. The solution I used is to spam .replace either regex or normal String until I get the behavior I want. I know it's really not optimized and I need to solve it in another way but I didn't think that it was the reason I couldn't eval big numbers.
and yeah thanks I will close the issue. Thanks again for your great library and support.

**Comment by kim24** [comment]
My bad. well thank you both @uklimaschewski for creating this library and @RobertZenz for contributing.
Thanks for the suggestion. I will try mXparser.
