### ISSUE TITLE
Supplying context to eval

### ISSUE THREAD

**Issue by eklinger** [uklimaschewski/EvalEx#189]
Hello
I would like to have a boolean expression but need additional context for the eval method to evaluate the expression. For example,

(5 AND 9) OR 3
And then pass in a Collection to eval() which would invoke contains() on the collection to evaluate the result of the literal. Is this possible?
Thank you
Evan

**Comment by RobertZenz** [comment]
I have a hard time understanding what you want to do, something like this maybe?

    Expression expression = new Expression("(x and y) or z")
            .with("x", "1")
            .with("y", "0")
            .with("z", "1");
    
    expression.eval() == 1

**Comment by RobertZenz** [comment]
Oh, no. As far as I can see the literal value wins over a set variable when parsing, so it never tries to replace them with the variable.

You could "pre-process" the expression with something like this:

```java
"(5 and 7) or 9".replaceAll("([0-9]+)", "x$1") == "(x5 and x7) or x9"
```

And these you can set as variables on the expression.

**Comment by RobertZenz** [comment]
I don't think that adding such a feature would be feasible or easily possible. So I'm closing this.
