### ISSUE TITLE
Compare two expressions and check if they are equals.

### ISSUE THREAD

**Issue by akshaymhetre** [uklimaschewski/EvalEx#192]
Is there any method to check if two given expressions are equal or not?
For example, a/(b * c) == a/(c * b)

**Comment by uklimaschewski** [comment]
Hello Akshay, no there is no such method.

**Comment by RobertZenz** [comment]
`equals` could be implemented for that. The question is, what should factor into equality? The expression seems clear (the parsed one, that is), but should set variables/operators/functions also be checked?

**Comment by uklimaschewski** [comment]
Out of scope for this library
