### ISSUE TITLE
Function evaluation is eager comparing to operators and other nodes, which are lazy

### ISSUE THREAD

**Issue by gnembon** [uklimaschewski/EvalEx#194]
in 
https://github.com/uklimaschewski/EvalEx/blob/37f409ffe83231c813c486b5482b655e641791ba/src/main/java/com/udojava/evalex/Expression.java#L1350
lazyEval is explicitly called. It should have the same 'lazy' behaviour as operators (which also technically also functions)
The issue surfaces if the package is extended to support assignments to variables, for example in the following case:
(initial context, a=0)
" a=1 ; if(a,1,2) " 
the value is incorrectly given as '2', because the IF statement is evaluated before RPN tokens run out.
(I added  assignment operator, and ';' operator)

**Comment by RobertZenz** [comment]
True. From the top of my head I'd know of three ways to fix that.

 1. `LazyFunction`s should return an appropriate `LazyNumber` which is being evaluated lazily.
 2. `LazyFunction` should extend `LazyNumber` and can so be pushed onto the stack and will be evaluated later.
 3. `AbstractLazyFunction` is extended to implement `lazyEval` and return a `LazyNumber` which wraps a `protected abstract` method.

Neither of these are very thrilling...but maybe I missed something there.

**Comment by gnembon** [comment]
I just replaced it with the equivalent expression from the operator's code a few statements above. I see no difference between operators and functions especially already enrolled on the rpn list.
`case FUNCTION:
                    ILazyFunction f = functions.get(token.surface.toUpperCase(Locale.ROOT));
                    ArrayList<LazyValue> p = new ArrayList<>(!f.numParamsVaries() ? f.getNumParams() : 0);
                    // pop parameters off the stack until we hit the start of
                    // this function's parameter list
                    while (!stack.isEmpty() && stack.peek() != PARAMS_START)
                    {
                        p.add(0, stack.pop());
                    }

                    if (stack.peek() == PARAMS_START)
                    {
                        stack.pop();
                    }

                    stack.push(new LazyValue()
                    {
                        public Value eval()
                        {
                            return f.lazyEval(p).eval();
                        }

                        public String getString()
                        {
                            return String.valueOf(f.lazyEval(p).eval());
                        }
                    });
                    break;`

**Comment by gnembon** [comment]
The other benefit of dealing with all the results the same way, is that there is no need to cache RPN list - one could cache the last LazyNumber upon next eval, just call .eval() on the AST from the last LazyNumber value that is left after. I tested that on a 3d game of life scenario (20*20*20 of evaluations of a complex expression in the volume) and with RPN caching (current code) I was getting 110ms per iteration, and with caching of the AST, I was getting about 70ms per iteration

**Comment by gnembon** [comment]
I don't mind, just am really busy at the moment with things. Plus I would need to learn how that change would affect tests because in this solution RPN is only a temporary representation. The final cached representation is AST. Here is now I have done it so far:
https://github.com/gnembon/carpetmod/blob/5ec533ff6a158015bc8cdc3da028238ea6aa1ba4/src/main/java/carpet/script/Expression.java#L1353
