### ISSUE TITLE
(1>=1) && ("ABC"!="BAKOKJ") 

### ISSUE THREAD

**Issue by sebahattinkoc** [uklimaschewski/EvalEx#196]
Can we use string in expression ?

**Comment by noumanjamil16** [comment]
@sebahattinkoc any luck so far for string comparison?

**Comment by noumanjamil16** [comment]
@FauxFaux @RobertZenz  can we do this string comparison? Can we achieve anything like this through IF(("ABC"=="ABC")||(5>3))

**Comment by RobertZenz** [comment]
I *still* ain't got any overview of what the String-Support actually can do, never had, not sure why.

The most hackiest way I can think of is:

 * Extend `BigDecimal` to hold a `String`.
 * Extend the `==` operator to check for this custom class, and implement logic according to it.
 * Set the extended `==` operator on the `Expression`.

There might be a better way, though, but as I said, I ain't got any idea how the String-Support actually looks like, never got anything to do with it. @uklimaschewski Can you give us a short overview, maybe?

**Comment by noumanjamil16** [comment]
@RobertZenz can you give an example of doing this as you describe above?

**Comment by RobertZenz** [comment]
From the top of my head, like this (pseudo-Java):

```java
public class StringBigDecimal extends BigDecimal
    protected String stringValue;

public class StringBigDecimalAwareEqualsOperator implements Operator
    public BigDecimal eval(BigDecimal a, BigDecimal b) {
        if (a instanceof StringBigDecimal && b instanceof StringBigDecimal) {
            return String comparison;
        }
        
        return default logic.
    }

expression.addOperator(new StringBigDecimalAwareEqualsOperator());
```

Something like that...
