### ISSUE TITLE
support continuous unary operators

### ISSUE THREAD

**Issue by tinylamb** [uklimaschewski/EvalEx#197]
eval expressions for examples  (check with Python)

> ++1 , --1, +-1, -+1

Tokenizer add  previousToken.type == TokenType.UNARY_OPERATOR

```
if (previousToken == null 
|| previousToken.type == TokenType.OPERATOR
|| previousToken.type == TokenType.OPEN_PAREN 
|| previousToken.type == TokenType.COMMA
||  previousToken.type == TokenType.UNARY_OPERATOR) {
    token.surface += "u";
    token.type = TokenType.UNARY_OPERATOR;
}
```

shuntingYard add previousToken.type != TokenType.UNARY_OPERATOR

```
case UNARY_OPERATOR: {
if (previousToken != null 
&& previousToken.type != TokenType.OPERATOR
&& previousToken.type != TokenType.COMMA 
&& previousToken.type != TokenType.OPEN_PAREN
 && previousToken.type != TokenType.UNARY_OPERATOR) {
throw new ExpressionException("Invalid position for unary operator " + token + " at character position " + token.pos);
}
```

**Comment by RobertZenz** [comment]
Is that already a patch for it? Can you come up with a merge request so that one can easily run the unit tests against it?

Also I could swear that there already was a ticket for pre/post increment support, but I can't find it anymore.

**Comment by tinylamb** [comment]
I have pushed a merge request. And there is another issue, 
I think COMPARISON_OPERATOR's leftAssoc should be TRUE, but not FALSE.
for example 

```
1>1>1  equals (1>1)>1 = FALSE,
1>1>1 not equals 1>(1>1)=TRUE
```

**Comment by RobertZenz** [comment]
A better example might be this:

    3 > 1 > 2 == 3 > (1 > 2)
    
    (3 > 1) > 2 == false
    3 > (1 > 2) == true

[Wolfram Alpha also says that this expression should be false](https://www.wolframalpha.com/input/?i=3+%3E+1+%3E+2). But that's quite a change to consider.

**Comment by tinylamb** [comment]
That is to say, COMPARISON_OPERATOR's leftAssoc should be TRUE.
follow this paper, logical operator's associativity also from left to right.
[Java Operators: Precedence and Associativity](http://www.cs-fundamentals.com/java-programming/java-operators-precedence-and-associativity.php)

**Comment by uklimaschewski** [comment]
This is an incompatible change, but I would consider it as a bug, which needs to be fixed.
I would accept a pull request on this one.

**Comment by tinylamb** [comment]
> A better example might be this:
> 
> ```
> 3 > 1 > 2 == 3 > (1 > 2)
> 
> (3 > 1) > 2 == false
> 3 > (1 > 2) == true
> ```
> [Wolfram Alpha also says that this expression should be false](https://www.wolframalpha.com/input/?i=3+%3E+1+%3E+2). But that's quite a change to consider.

I think Wolfram Alpha parse this kind expression as following
```
3>1>2   as  (3>1) and (1>2)
3>=2>=2 as (3>=2) and (2>=2)
```
take 3>=2>=2 for example,
if do (3>=2)>=2, the result is False
but Alpha tells [True](https://www.wolframalpha.com/input/?i=3%3E%3D2%3E%3D2)
