### ISSUE TITLE
How to add support for ternary operator?

### ISSUE THREAD

**Issue by cncodeguru** [uklimaschewski/EvalEx#204]
Hi all,

This tool is wonderful. However in the project that I am working on. We need to use ternary operator in expressions like below. Can someone let me know if it's possible with EvalEx? It doesn't seem to fit the Operator interface.

booleanExpression ? expression1 : expression2

Thanks a lot.

Gregory

**Comment by squeek502** [comment]
`IF(booleanExpression, expression1, expression2)` isn't sufficient?

**Comment by cncodeguru** [comment]
The project uses [JEL](https://www.gnu.org/software/jel/), which supports ternary operator. However JEL doesn't support '+', '-', '*', '/' etc. on BigDecimals. That's why I am considering EvalEx. My goal is to keep existing expressions unchanged. I am trying [JEXL](http://commons.apache.org/proper/commons-jexl/) at the moment. Looks promising.

**Comment by RobertZenz** [comment]
I know it is frowned upon, but both of these characters are not used right now, so you could get away with "pre-processing" the expression with a regular expression.

    (?<EXPRESSION>[^(]+)\?(?<POSITIVE>[^:]+):(?<NEGATIVE>[^)]+)

I mean, that one is very crude, but might work. Or you actually parse the expression for it.

I also thought that you might be able to implement it using the operator support, but that's not really possible, at least not easily.
