### ISSUE TITLE
Unable to evaluate String expression

### ISSUE THREAD

**Issue by HemendraGangwar** [uklimaschewski/EvalEx#208]
### How can i evaluate string expression like

**new Expression(" (15=15)   &&  (aaa=xyz)  ").eval()**

as right now we are getting this error
[](url)
Attempt to read from field 'com.udojava.evalex.Expression$TokenType com.udojava.evalex.Expression$Token.type' on a null object reference

**Comment by RobertZenz** [comment]
Mh, that's working for me under the condition that `aaa` and `xyz` are being set as variables.

```java
new Expression(" (15=15) && (aaa=xyz) ")
        .with("aaa", "1")
        .with("xyz", "1")
        .eval()
```
