### ISSUE TITLE
How about to reolve an improper fraction or mixed fractions

### ISSUE THREAD

**Issue by PeterHan1981** [uklimaschewski/EvalEx#21]
Hello,uklimaschewski:
thank u for you. Because your lib help me for resolving a question. But how to resolve a fraction like 11/2, but I mean 1 and 1/2 , the real value is 3/2 , but your lib mean it 11/2, can you have some proposes?

**Comment by uklimaschewski** [comment]
Peter, if you want 1 **and** 1/2, you would use 1 + 1/2.

**Comment by PeterHan1981** [comment]
Thanks uklimaschewski!
