### ISSUE TITLE
Max normal power doesn't work properly

### ISSUE THREAD

**Issue by Fireztonez** [uklimaschewski/EvalEx#213]
Hello,
In the config file `enchantment_module.cfg` I have set the `S:"Max Normal Power"=20.0`, but when I place regular bookshelf around the enchanting table, I can get a maximum of enchant LVL 64, with 32 bookshelf (So, power 32).

Having possibility of more than 2x the normal enchanting power with regular bookshelf look a little bit too much I think, but I want to be able to get with Hellshelf a maximum of power 128.

Unless I do not understand what do you mean by `Normal Source`, I think this is a bug.

**Version:**
Minecraft Forge: 1.12.2 - 14.23.5.2838
Apotheosis: 1.10.2

Thank's

**Comment by RobertZenz** [comment]
I think you took a wrong turn somewhere. This project is a about a software library which provides means for arbitrary precision calculation, it has ***nothing*** to do with Minecraft or any mod in any way.

**Comment by squeek502** [comment]
Looks like he found the right repo: https://github.com/Shadows-of-Fire/Apotheosis/issues/67

**Comment by uklimaschewski** [comment]
:-D

**Comment by Fireztonez** [comment]
Yeah, look like Github send the issue on the wrong repo some how... This is very very stange, but i'm pretty sure I have send the message to the Apotheosis repo the first time, but after looking again the issue is not there so I write again... I don't know, but I think github have somes issue, or i'm possibly totally crazy!!
