### ISSUE TITLE
Is it possible to add Strings as operators (e. g. AND, OR)?

### ISSUE THREAD

**Issue by Roland09** [uklimaschewski/EvalEx#217]
Is it possible to allow a custom operator to be a string? Example: replace && with AND.

I tried it with this:

```
Expression e = new Expression("if( a == 1 AND b == 1, 1, 0)");

e.addOperator(new AbstractOperator("AND", Expression.OPERATOR_PRECEDENCE_AND, false, true) {
  @Override
  public BigDecimal eval(BigDecimal v1, BigDecimal v2) {
	
	boolean b1 = v1.compareTo(BigDecimal.ZERO) != 0;
	
	if (!b1) {
	  return BigDecimal.ZERO;
	}
	
	boolean b2 = v2.compareTo(BigDecimal.ZERO) != 0;
	return b2 ? BigDecimal.ONE : BigDecimal.ZERO;
  }
});

BigDecimal result = e.with( "a", "0").and( "b","1").eval(); 

System.out.println(result);
```

But that results in the exception: _Function if expected 3 parameters, got 5_

**Comment by uklimaschewski** [comment]
If I see it correctly:
With the current implementation of the tokenizer, an operator must not contain a letter.
In your example, the validator thinks this is a variable and gets confused.
I think it would be nice to have that possibility. Shouldn't be too hard to implement.
At the moment, the tokenizer thinks anything with a letter is a function or variable.
There should be an additional check, if there is an operator defined with that name and then return the right token type:

https://github.com/uklimaschewski/EvalEx/blob/990e10f86b08cb3c4f87cf4a646121750a95fb30/src/main/java/com/udojava/evalex/Expression.java#L454-L467

**Comment by uklimaschewski** [comment]
@Roland09 can you please check version 2.3?
I have added this possibility to this version.
If it is OK for you, you can close this issue.

**Comment by Roland09** [comment]
Awesome, thank you very much for your efforts!

**Comment by Roland09** [comment]
@uklimaschewski found a bug. When you use braces in a condition check, the string operator is seen as a function. 

This works:

`Expression e = new Expression( "if( a=0 and b=0, 0, 1)");`

This doesn't and results in an excpeption "Unknown function and at character position 11":

`Expression e = new Expression( "if( (a=0) and (b=0), 0, 1)");`

Full example:

   ```
 // Expression e = new Expression( "if( a=0 and b=0, 0, 1)"); // ok
    Expression e = new Expression( "if( (a=0) and (b=0), 0, 1)"); // not ok

    e.addOperator(new AbstractOperator("AND", Expression.OPERATOR_PRECEDENCE_AND, false, true) {
      @Override
      public BigDecimal eval(BigDecimal v1, BigDecimal v2) {
          boolean b1 = v1.compareTo(BigDecimal.ZERO) != 0;
          if (!b1) {
              return BigDecimal.ZERO;
          }
          boolean b2 = v2.compareTo(BigDecimal.ZERO) != 0;
          return b2 ? BigDecimal.ONE : BigDecimal.ZERO;
      }
    });

    
    BigDecimal result = e.with("a", "0").and("b", "0").eval();
    System.out.println(result);
```

**Comment by Roland09** [comment]
@uklimaschewski I guess the solution to the mentioned bug is to simply switch the if-clause, i. e. instead of this:

```
if (ch == '(') {
	token.type = TokenType.FUNCTION;
} else if (operators.containsKey(token.surface)) {
	token.type = TokenType.OPERATOR;
} else {
	token.type = TokenType.VARIABLE;
}
```

it should be this

```
if (operators.containsKey(token.surface)) {
	token.type = TokenType.OPERATOR;
} else if (ch == '(') {
	token.type = TokenType.FUNCTION;
} else {
	token.type = TokenType.VARIABLE;
}
```

**Comment by uklimaschewski** [comment]
@Roland09 I have created version 2.4 with your proposed fix. Feel free to open a pull request directly next time. :-)
