### ISSUE TITLE
ASIN, ACOS and ATAN

### ISSUE THREAD

**Issue by yoavst** [uklimaschewski/EvalEx#22]
Also, I think it is a good idea to add this line to all trigo functions:
```java
if (d == 0) return BigDecimal.ZERO;
```

**Comment by talonos2** [comment]
I would also like an ATAN function. My two cents.

**Comment by uklimaschewski** [comment]
I have added these functions, [Adrian](http://udojava.com/2012/12/16/java-expression-parser-evaluator/comment-page-1/#comment-4515) was so kind to implement them.
