### ISSUE TITLE
How is getExpressionTokenizer supposed to be used?

### ISSUE THREAD

**Issue by dplusj** [uklimaschewski/EvalEx#226]
Hi, I am looking to use getExpressionTokenizer to get all tokens and replace some of them before the final evaluation. For example convert "2\*2k" to "2\*2\*1000".  Previously this method returns type of List\<String\>, but now it returns type of List\<Token\> while Token is an inner private class. Can you please make this Token class public or show me how to get my example working again in the new API? 

Thanks.

**Comment by RobertZenz** [comment]
There's #182 which seems to be the same request.

**Comment by RobertZenz** [comment]
This should be fixed with [2.5](https://github.com/uklimaschewski/EvalEx/releases/tag/2.5), which makes `Token` `public`.
