### ISSUE TITLE
Degree and Radian are reversed while evaluating a math expression

### ISSUE THREAD

**Issue by Abdelkarim24** [uklimaschewski/EvalEx#230]
So when I try : 
RAD(7) = 0.1221730476396031
DEG(7) = 401.0704565915763

Normally the result should be : 
RAD(7) =  401.0704565915763
DEG(7) = 0.1221730476396031

**Comment by RobertZenz** [comment]
I don't follow, sorry. `RAD` and `DEG` are "convert this value to" functions. `RAD` is converting degrees to radians, and `DEG` is converting radians to degrees, and both work as far as I can see.

**Comment by Abdelkarim24** [comment]
Sorry, my question was messed up I just edited it.

So for example when I use google : 

![image](https://user-images.githubusercontent.com/56474075/73381116-82487a80-42c5-11ea-9ebd-cf14a62586d3.png)

VS 
Evalex 
RAD(7) = 0.1221730476396031

**Comment by uklimaschewski** [comment]
The RAD() function converts an angle measured in degrees to an approximately equivalent angle measured in radians.
It does not convert radians to degrees. That's what you did on Google.
