### ISSUE TITLE
Repeatability of random expressions

### ISSUE THREAD

**Issue by showbags** [uklimaschewski/EvalEx#234]
The current implementation of the random function is not repeatable. This should not normally be an issue but it would be nice for random results to be deterministic for the purposes of regression testing. Would it be OK to pass a java.util.Random as a constructor argument to achieve this?

public Expression(String expression, MathContext defaultMathContext, Random random)

**Comment by RobertZenz** [comment]
You can always override the default `RANDOM` function with your own. Something like this:

```java
Random random = new Random(0l);
Expression expression = new Expression("RANDOM()");
expression.addFunction(new Function("RANDOM", 0) {
	@Override
	public BigDecimal eval(List<BigDecimal> parameters) {
		return new BigDecimal(random.nextDouble(), mathContext);
	}
});
```

**Comment by showbags** [comment]
Yep, I like it. Thanks.
