### ISSUE TITLE
Easier Absolute Value and Factorial

### ISSUE THREAD

**Issue by NumberC** [uklimaschewski/EvalEx#236]
Hello! This is a feature request. Instead of having to write `FACT(x)` or `ABS(x)`, is it possible to add a feature where users can write `x!` or `|x|` and return the same result? I'm willing to help if needed. Thank you!

**Comment by RobertZenz** [comment]
This is partially a duplicate of #126, which is concerned with right-hand unary operators, and maybe #180.

But I don't believe that there is a ticket for having an operator *around* the variable.

**Comment by RobertZenz** [comment]
Oh, and to rehash previous discussions about this, the parser does not support either case as far as I am aware.

**Comment by uklimaschewski** [comment]
I think this will be too complex to implement, especially that |a| Syntax is far off the map.

**Comment by uklimaschewski** [comment]
Fixed with #257
