### ISSUE TITLE
add Function is giving issue

### ISSUE THREAD

**Issue by avinashag19** [uklimaschewski/EvalEx#239]
Hi Uklimaschewski,

First of all great kudos to writing a such a great code. While i was trying to implement i got an error on the line pasted below

 public com.udojava.evalex.Function addFunction(com.udojava.evalex.Function function) {
        return (com.udojava.evalex.Function) functions.put(function.getName(), function);
    }

Error : The method put(String ,LazyFunction) in the type Map<String,LazyFunction> is not a applicable for the arguments(String, Function).

Please reply if possible...will be waiting for your reply.

**Comment by RobertZenz** [comment]
Can you give us the complete stacktrace? That does not sound like something that should happen.

**Comment by RobertZenz** [comment]
From purely looking at the code, I can't see anything wrong there.

The only idea I have is that this is a classloader issue. Is it possible that `Expression` and whatever `Function` you're trying to add are being loaded by two different classloaders?

**Comment by avinashag19** [comment]
Hi Uklimaschewski/Evalex,

My apologies, it was my mistake. I resolved the issue.
SOrry for taking your time.

**Comment by uklimaschewski** [comment]
You're welcome
