### ISSUE TITLE
IF evaluation

### ISSUE THREAD

**Issue by unficyp** [uklimaschewski/EvalEx#24]
Hi,

why does IF(TRUE,1,1/0) throw a division by zero error ? Seems like 1/0 is evaluated regardless of
the result of the if condition ?

thanks!
gerald

**Comment by uklimaschewski** [comment]
The expression 1/0 is evaluated first, through the RPN parser. The IF(condition, value1, value2) is just a normal function, like MIN(a,b), so the parameters are evaluated before the function is called.
