### ISSUE TITLE
How to solve float number problems with math placeholder.

### ISSUE THREAD

**Issue by johnsoncui02** [uklimaschewski/EvalEx#241]
This command will help me check the number of times players completed the quest. It works well when the player completes quests in even numbers, but when it's odd numbers it would only give me 1 prismarinecrystals. Is there a way where I can make it not only give me 1 for every odd number?

`cmi give {player} prismarinecrystals {math:(%questcreator_completions_zombie_expert%/2)+1}`

**Comment by RobertZenz** [comment]
Could it be that you took a wrong turn somewhere? This is about a mathematical expresseion parser and evaluator called  EvalEx...not sure what you got there, but doesn't look like an expression EvalEx would parse.

Oh, I know, it's this Minecraft-thingy, right? Yeah, we don't do that, that's not us.
