### ISSUE TITLE
String variables in functions

### ISSUE THREAD

**Issue by eduardo-moreira** [uklimaschewski/EvalEx#244]
When a function has a String variable as param, eval consider the name of variable.

For eg:

```
Expression expression = new Expression("IN (myValue, \"CC\", \"ABC\")");
expression = expression.with("myValue", "CC");
```

It will return 1, but 0 (ZERO) is expected.

To fix it, we can change the Expression class, method eval:

```
case VARIABLE:
                    if (!variables.containsKey(token.surface)) {
                        throw new ExpressionException("Unknown operator or function: " + token);
                    }

                    stack.push(new LazyNumber() {

                        public BigDecimal eval() {
                            LazyNumber lazyVariable = variables.get(token.surface);
                            BigDecimal value = lazyVariable == null ? null : lazyVariable.eval();
                            return value == null ? null : value.round(mc);
                        }

                        public String getString() {
                            // return token.surface;   RETURN THE NAME OF THE VAR?
                            LazyNumber lazyVariable = variables.get(token.surface);
                            return lazyVariable.getString();
                        }
                    });
```

**Comment by SirError** [comment]
is there an easy way to override this method with this fix? 

> 
> 
> When a function has a String variable as param, eval consider the name of variable.
> 
> For eg:
> 
> ```
> Expression expression = new Expression("IN (myValue, \"CC\", \"ABC\")");
> expression = expression.with("myValue", "CC");
> ```
> 
> It will return 1, but 0 (ZERO) is expected.
> 
> To fix it, we can change the Expression class, method eval:
> 
> ```
> case VARIABLE:
>                     if (!variables.containsKey(token.surface)) {
>                         throw new ExpressionException("Unknown operator or function: " + token);
>                     }
> 
>                     stack.push(new LazyNumber() {
> 
>                         public BigDecimal eval() {
>                             LazyNumber lazyVariable = variables.get(token.surface);
>                             BigDecimal value = lazyVariable == null ? null : lazyVariable.eval();
>                             return value == null ? null : value.round(mc);
>                         }
> 
>                         public String getString() {
>                             // return token.surface;   RETURN THE NAME OF THE VAR?
>                             LazyNumber lazyVariable = variables.get(token.surface);
>                             return lazyVariable.getString();
>                         }
>                     });
> ```

**Comment by eduardo-moreira** [comment]
I cloned the source project in my workspace and use my version of Expression class

**Comment by SirError** [comment]
> 
> 
> I cloned the source project into my workspace and use my version of Expression class

Oh, I see, 
Could you please provide a PR so we wouldn't have to keep local copies?
or if you don't mind I could send a PR with your fix.

please let me know it, thanks!
