### ISSUE TITLE
Wrong operator priority (unary minus)

### ISSUE THREAD

**Issue by Cubxity** [uklimaschewski/EvalEx#245]
Evaluating "-12^2" results in 144, the expected answer is -144 due to power operator having the priority, so it should be interpreted as `-(12^2)` instead of `-12 * -12`.

See: [Wolframe Alpha](https://www.wolframalpha.com/input/?i=-12%5E2)

**Comment by uklimaschewski** [comment]
See discussion on issue #231. I will close this as a duplicate.
