### ISSUE TITLE
multiplication distributive law

### ISSUE THREAD

**Issue by zxp209** [uklimaschewski/EvalEx#246]
Is there any possible to get "multiplication distributive law" express?
for example,
 input : (A+B)*(C+D)
output: A*C+A*D+B*C+B*D

I knew matheclipse ,but it run too slowly

**Comment by RobertZenz** [comment]
This library is only concerned with parsing and evaluating mathematical expressions, not modifying/simplifying/transforming them. So, I'd say no.
