### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by 0moemura0** [uklimaschewski/EvalEx#247]
It has a crash after division by 0. Sorry, if it's my program fault, but anyway.

**Comment by RobertZenz** [comment]
If you mean that an exception is being thrown, yes, that is intended. A division by zero has an undefined result, therefor throwing an exception is the best course of action for the library to treat that situation. You will have to catch and handle that exception in your code.

**Comment by 0moemura0** [comment]
Thanks!

**Comment by RobertZenz** [comment]
"Potential"? Not that I know of. However, you can always evaluate the expression and catch the resulting Exception and work from there. It depends on what exqctly you'd like to do, though.
