### ISSUE TITLE
Dart port

### ISSUE THREAD

**Issue by wdavies973** [uklimaschewski/EvalEx#249]
In case anyone is interested, I have ported this library to Dart and am actively maintaining it.

https://github.com/RobluScouting/EvalEx

**Comment by RobertZenz** [comment]
@uklimaschewski Would you be against adding this to the README?

**Comment by uklimaschewski** [comment]
@RobertZenz @wdavies973 no problem with it

**Comment by RobertZenz** [comment]
I've added a "Similar Projects" section to the bottom, and also added exp4j (because I remember sending people over there).
