### ISSUE TITLE
Maven Release?

### ISSUE THREAD

**Issue by connollyst** [uklimaschewski/EvalEx#25]
Hi Udo,

This project looks great, thanks for your effort! We'd like to use EvalEx in one of our projects but see it hasn't been released to Maven central. Would you be able to release this?

The only alternative for us would be to download the source, build it, upload it to our own repository and work off of that. But that sort of defeats the dependency management feature of Maven and we'd opt to use a different tool.

I'd be happy to help you release this if you're new to the process.

Best,
Sean

**Comment by uklimaschewski** [comment]
Give me a few days to look into some options for this. This whole maven central administrative tasks are so complex and bureaucratic.

**Comment by connollyst** [comment]
Great, thanks Udo.
Maven releases are a pain, lots of hoops to jump though to get started. I always go through sonatype, once you have everything set up it's pretty straightforward using the ``maven-release-plugin``. Let me know how I can help.

Cheers,
Sean

**Comment by uklimaschewski** [comment]
I started a ticket for a new project on Sonatype, now I have to wait ...

**Comment by jitpack-io** [comment]
Hi!
In the meantime EvalEx is already available on JitPack as a Maven artifact: https://jitpack.io/#uklimaschewski/EvalEx/f3b0f865b1 : )
Would be a bit easier with a GitHub release, btw.

**Comment by connollyst** [comment]
Very cool, I had never heard of JitPack, what a neat idea. Let me know if you do get it released into Maven Central though as it would be one less repository in my pom.

Cheers,
Sean

**Comment by uklimaschewski** [comment]
Yes, jitpack looks cool. I have a Sonatype account/project set up now. I hope to find some time this weekend to try to get some artifacts up there.

**Comment by connollyst** [comment]
Great, thanks for taking the time.

**Comment by uklimaschewski** [comment]
I plan to use [Rultor](http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html) for the Maven Central releases, which looks pretty neat. I though I had set up everything corerctly, but I am getting a gpg error now. I opened a new issue at https://github.com/yegor256/rultor/issues/853, I will have to wait to know what I did wrong.
You can see my tests with Rultor at https://github.com/uklimaschewski/EvalEx/issues/26

**Comment by uklimaschewski** [comment]
Hooray! I managed to built the relase artifacts and upload them to my sonatype staging area.
Now we have to wait until they get synchronized with maven central.
I commented on my initial ticket at sonatype, so they should hopefully enable synchronization soon.

**Comment by connollyst** [comment]
That's great, thanks for taking the time Udo.

**Comment by brendanator** [comment]
When I search for EvalEx in maven central it doesn't seem to be there yet. Is it available somewhere?

**Comment by connollyst** [comment]
I still don't see it either. I was looking under the package ``com.udojava`` but find nothing. Usually it takes, at most, an hour to sync servers. Maybe you didn't close out the deploy repository with Sonatype?

**Comment by uklimaschewski** [comment]
There was a problem in verifying upon close, some parts were missing. I have to check it tomorrow.

**Comment by uklimaschewski** [comment]
I (hopefully) fixed all problems. Now it looks like we have to wait a bit longer than the usual hour or so, because it is the first release to maven central and it will need some manual administrator action.

**Comment by uklimaschewski** [comment]
EvalEx version 1.0 is now available through maven central.

**Comment by connollyst** [comment]
Awesome, much appreciated Udo =)
Looking forward to working with your code.

**Comment by brendanator** [comment]
Thanks Udo!!
