### ISSUE TITLE
Too many numbers or variables

### ISSUE THREAD

**Issue by DianaZhao** [uklimaschewski/EvalEx#252]
I tested with a generated logical expression with 100 variables

true or false or true or false or true or false or false or false or false or false or false or false or true or true or true or true or true or true or false or true or true or false or true or true or true or true or false or true or true or true or false or false or true or false or true or true or true or false or false or false or true or false or false or true or true or false or true or true or true or true or true or false or true or true or true or true or false or true or true or false or true or false or true or true or false or false or true or true or false or true or false or true or true or false or true or false or true or false or false or false or false or true or false or false or true or true or true or false or true or true or false or false or false or false or true or false or false or false or true or true

com.udojava.evalex.Expression$ExpressionException: Too many numbers or variables

**Comment by uklimaschewski** [comment]
'or' is not an operator, use ||
