### ISSUE TITLE
Anyway to make trigonometric functions implicit?

### ISSUE THREAD

**Issue by walsus** [uklimaschewski/EvalEx#253]
I have 2 questions:

1- Can I make this expression acceptable ?   **6SIN(8)**    instead of **6xSIN(8)**   ?
2- Can I let **Sin(8**   be automatically evaluated when at the end of the expression ?without the need to add a closing parenthesis ?

**Comment by uklimaschewski** [comment]
1- This would require some changes in the tokenizer, I guess. Depending on how many cases you want to support, this could be rather simple or quite complex.

2- You could do this outside EvalEx. Count the number of parentheses in the string. Then add the missing parentheses at the end, if there is a mismatch.

**Comment by RobertZenz** [comment]
See #64 and #123 for pevious discussions.

**Comment by uklimaschewski** [comment]
Oh, thanks @RobertZenz, I totally forgot about #123
