### ISSUE TITLE
Is there anyway to make exp.eval() return null when the expression is incomplete ?

### ISSUE THREAD

**Issue by walsus** [uklimaschewski/EvalEx#254]
Dears,

Supposing that an incomplete expression was fed like this :  

```
Expression exp=new Expression("561");
result = exp.eval();

```
 The resulting value that is getting returned by the exp.eval()   is actually also 561   
mm.. Is there a simple way to alter eval() in a way to simply return null in case no complete expression string was passed to it ?

Thank a lot.

**Comment by uklimaschewski** [comment]
"561" is a perfectly valid expression, it is not incomplete. Therefore returning null doesn't make sense for EvalEx.
If you want to add such behavior, you could check the expression with expression.getExpressionTokenizer(). I returns a copy of the internal tokenizer. With the tokenizer you are able to count the tokens. Your above example has a count of one.
