### ISSUE TITLE
Use Travis CI instead of Rultor to release to Maven Central

### ISSUE THREAD

**Issue by uklimaschewski** [uklimaschewski/EvalEx#260]
Looks like @rultor, which I used for creating releases and deploying to Maven Central is not working anymore. At least not with the current setup, probably something has changed.
Instead of fixing rultor, consider using Travis CI also for this job.

**Comment by srinisubramanian** [comment]
@uklimaschewski  I need the maven jar with the latest fix regarding the String variable that was merged #244 .  Any idea when the artifact will be published to Maven or should I just go with a locally compiled jar?  Thanks for your assistance in this

**Comment by uklimaschewski** [comment]
Version 2.6 has been published to Maven Central. It can already be referenced in builds, but it may take a few hours until it also is visible in Maven Central search.

From now on, every push to master will create and publish a snaphost release to [Sonatype Nexus repository manager](https://oss.sonatype.org/#nexus-search;classname~EvalEx).

To create a release that will be published also to Maven Central, create and push a tag from master branch, e.g.:
```
$ git tag 2.7
$ git push origin 2.7
```
