### ISSUE TITLE
Validate only a String

### ISSUE THREAD

**Issue by rider87** [uklimaschewski/EvalEx#268]
Hi,

I haven´t found any solution if I would like to check only a String?
E.g. I want to check:

String myString = "TEST = TEST"

How is this possible?

**Comment by uklimaschewski** [comment]
You can do this with a custom string compare function, because strings are only supported in function parameters.
Example: https://github.com/uklimaschewski/EvalEx#custom-functions-with-string-parameters

**Comment by rider87** [comment]
Thanks... but then I need something like:
`STRINGEQUAL("String1", "String2")`

Is there no possibility to check it like:
`"TEST = TEST"`

Thanks in advance

**Comment by rider87** [comment]
Please see also Java Thread:
https://www.java-forum.org/thema/string-expression-mit-java-validieren-true-false.192890/#post-1261836

**Comment by rider87** [comment]
@uklimaschewski do we need to open this again?
