### ISSUE TITLE
IF-Expression (both cases are executed)

### ISSUE THREAD

**Issue by kaidrewes** [uklimaschewski/EvalEx#27]
Hello Udo,
thanks for your project. 
I have a problem with the IF-Expression. If a condition evaluates to false both expressions are executed. 

example:
value1 = 0;
value2 = 2;
IF(value1>0,value2/value1,0)

value2/value1 (2/0) will be executed. 
In this case Java throws an "ArithmeticException: Division by zero".

request:
First the condition should be tested and then one of the two values should be excuted.

Can you fix that problem? 

I am looking forward to hearing from you.

Best regards,
Kai

**Comment by squeek502** [comment]
Related: #24

**Comment by uklimaschewski** [comment]
The `IF` is a normal function, like e.g. `MAX`. The function parameters are evaluated before the function is called. It is just a helper, not a special expression like in programming languages. Parameters to functions are always values and not expressions.
