### ISSUE TITLE
Detect whether an Expression is a simple number

### ISSUE THREAD

**Issue by danielpeintner** [uklimaschewski/EvalEx#293]
Question: I was wondering whether there is an *easy* way to detect with EvalEx whether an expression is a simple number?

Let me describe in more details my use-case. I have two input values for expressions which get multiplied in the end.
For example:
expression1: `12+3`
expression2: `5-3`

Hence what I do is to is to concatenate the strings (if valid): `(expression1) * (expression2)`
Note: To be on the safe side I need to add brackets around it. I also show the "resulting" expression to the user. In this case `(12+3) * (5-3)`

This bring me to the actual question. In most of the cases people insert simple numbers like
expression1: `8`
expression2: `9`
and the results looks like this: `(8) * (9)` 

People wonder why these brackets are added since it would be nicer looking to have in *this* case `8 * 9`.

I noticed there is a [`isNumber(...)`](https://github.com/uklimaschewski/EvalEx/blob/76807e094f16be7636a064d36f5e089aaeb92114/src/main/java/com/udojava/evalex/Expression.java#L1331) function. Unfortunately it is protected. 
Is there another way to achieve what I am looking for?

Thanks for any advice and your library in the first place!

**Comment by RobertZenz** [comment]
You could always check whether the `String` only contains digits in your preprocessing logic, something like:

```java
private static final Pattern NUMBERS_ONLY_PATTERN = Pattern.compile("^[0-9]+$");

String expression = "5*9";

if (NUMBERS_ONLY_PATTERN.matcher(expression.trim()).matches()) {
    // Contains only numbers.
} else {
    // Contains also other characters.
}
```

**Comment by RobertZenz** [comment]
I don't think EvalEx really has a utility function for that which is exposed/public, and I'm unsure whether it should have it. Yes, it's of course part of the functionality, but defining whether your expression needs parentheses or not, should be part of your logic, in my opinion.

**Comment by danielpeintner** [comment]
I agree, of course I can write this part of the code myself. I was just seeing the internal method [isNumber(...)](https://github.com/uklimaschewski/EvalEx/blob/76807e094f16be7636a064d36f5e089aaeb92114/src/main/java/com/udojava/evalex/Expression.java#L1331) which could be made public.

Anyhow, thanks for your reply!
