### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sh1nchan** [uklimaschewski/EvalEx#32]
Hallo Udo,

die if() Formel hat einen kleinen Bug.
Wenn man if (true, -x+y,0) auswerten, möchte, dann kommt es zu einer Fehlermeldung.

**Comment by uklimaschewski** [comment]
In dem Ausdruck `if(true, -x+y,)` sind zwei Fehler:
1) `true` ist unbekannt, ausser man definiert es als variable mit dem Wert `1`. Sonst kommt es zu einer `NumberFormatException`.
2) "-x" ist in der Syntax von EvalEx nicht erlaubt, Prefix und Postfix Operatoren werden nicht unterstützt. Stattdessen `-1*x` verwenden, sonst kommt es zu einem Stack Fehler.

Folgendes funktioniert dann:

````Java
Expression expression = new Expression("if(true, -1*x+y,0)");
String result = expression.with("true","1").and("x", "2").and("y","3").eval().toPlainString();
assertEquals("1", result);
````
