### ISSUE TITLE
Feature Request: NULL als Konstante

### ISSUE THREAD

**Issue by sh1nchan** [uklimaschewski/EvalEx#33]
Hallo Herr Klimaschewski,
könnten Sie mir helfen,
evalEx so zu erweitern, dass man eine Konstante mit null hat.

Brauchen tue ich z.B. für eine IF-ELSE-Formel:
```java
	@Test
	public void testNullAsConstant()
	{
		String formel = "if(y==0, NULL, x/y)";
		Expression e = new Expression(formel);
		e.with("y", BigDecimal.ZERO);
		e.with("x", BigDecimal.TEN);
		e.with("NULL", (BigDecimal) null);
		
		// ------ VERIFY ------- //
		assertNull(e.eval());
	}
```
ich dachte man könnte mit Hinzufügen einer neuen "Variable" das Problem lösen:
m_variables.put("NULL", null);

Aber da bekomme ich auch ein NPE.

Vielen Dank im Voraus.

**Comment by uklimaschewski** [comment]
Mit ein wenig Gedult könnte man eventuell ein NULL Handling einbauen, das führt in dem beispiel aber nicht zum Ziel.
Die IF() Funktion evaluiert erst beide Parameter, bevor ein Wert zurück gegeben wird.
Es ist nicht so, das zuerst die Bedingung geprüft wird und dann erst der jeweilige Zweig.
Insofern würde, auch mit einem NULL Handling, obiger Ausdruck zu einer Division by Zero führen.
