### ISSUE TITLE
dynamic precision

### ISSUE THREAD

**Issue by Haeri** [uklimaschewski/EvalEx#34]
Hay Udo. Thank you very much for this amazing repository. This is exactly what I was looking for.

This is not a bug report, but rather a personal problem I ran into. Would be great if you could maybe help me out.

I am trying to get the right precision for every occasion:
1. A normal decimal number should have a a precision of 5
(1/3 = 1.33333)
2. A calculation with decimal numbers should orient on the largest decimal point and set the precision according to it:
(0.1234567 + 0.1234 = 0.2468567)
3. Big numbers should have the maximum precision:
(12345678 * 123456 =  1524148023168)

I have tried several things like setting the precision to 128, which gives me (3) and (2) but (1)  spammed the output with too many periodic "3"s. 

Could you maybe hint me in the right direction?

Thanks again for the amazing code
Liebe Grüsse Haeri

**Comment by uklimaschewski** [comment]
The problem, as I see it, is how EvalEx should determine what is a "normal" decimal number.
If it is just about periodic values, you can post-process the result and strip down the decimal digits.
But what about Expressions like `22/7`?
If it is just about "intelligent" rounding in division and multiplication, you could add custom functions for this, or even override the existing operators.
For example, the standard division is defined as:
````java
		addOperator(new Operator("/", 30, true) {
			@Override
			public BigDecimal eval(BigDecimal v1, BigDecimal v2) {
				return v1.divide(v2, mc);
			}
		});
````
in the `eval()` method, you could analyse both operands (`v1` and `v2`) and according to their decimal digits do a custom rounding. Then return the rounded `BigDecimal` value.

**Comment by Haeri** [comment]
I have to admit, I was thinking about the post process approach too, but I thought, surely there has to be a non hacky way, since what I am asking is the "normal" behavior of an calculator. 
But I might have to go with it. I just don't have the brainpower to implement my own functions.. Maybe someday someone smarter than me decides to commit a new "intelligent" rounding ;)
Thanks again.
