### ISSUE TITLE
setRoundingScale?

### ISSUE THREAD

**Issue by ebbe1991** [uklimaschewski/EvalEx#35]
Hallo,

ich habe ein Problem mit MathContext der Expression-Klasse:
Die Precision des MathContext bezieht sich auf alle Ziffern inklusive der Vorkommastellen, sodass meine Ergebnisse gegebenenfalls sehr ungenau werden (bei MathContext.DECIMAL32):
Könnte man vielleicht statt der Precision einen Scale setzen, sodass diese sich nur auf die Nachkommestellen beziehen? (setPrecision vs setScale?)

Ich glaube ich habe noch nicht verstanden, warum überhaupt mit einem MathContext gearbeitet wird (anstelle eines Scales mit RoundingMode), können Sie mir da weiterhelfen?

**Comment by uklimaschewski** [comment]
Den Scale kann man nicht global setzen, dazu dient die Funktion ROUND(), mit der man dediziert Ausdrücke oder Teilausdrücke runden kann. Als Rundungsmodus wird der Modus des MathContext benutzt.
