### ISSUE TITLE
Support for Unary operators

### ISSUE THREAD

**Issue by yoavst** [uklimaschewski/EvalEx#36]
So we could write `+5` or `-SQRT(9)`
Currently it throws exception.

**Comment by uklimaschewski** [comment]
This will require some tricky changes in the parser locgic. I will leave this issue open, maybe I will find some time, or there is a clever contributor who wants to earn eternal fame and honour ... ;-)

**Comment by yoavst** [comment]
I've wrote a parser that support unary operator in Kotlin. 
Here is my project - https://gitlab.com/yoav-sternberg/algebraEval (it was done for learning how to parse expressions, but yes it is based on EvalEx.), if someone want to port the unary part, you are welcome.

**Comment by uklimaschewski** [comment]
Thank you very much for this code snippet!

**Comment by micabytes** [comment]
'not'  or '!' as a unary operator would be nice, as that is pretty common in many expressions.

**Comment by Sub6Resources** [comment]
I would love to see this added to the project. It appears it hasn't been worked on recently.
