### ISSUE TITLE
How i can turn off the scientific notation for results?

### ISSUE THREAD

**Issue by Frietziek** [uklimaschewski/EvalEx#43]
Hi, first i have to say my congratulations for your project, very god job man. I am mading a simple calculator (my first Android app), and i have issues with the notation of results:
For example, if i do "10+10" instead of give me "20" as result it give me "2E+1".

You know how i cant fix it?

PD: sorry for my bad english

**Comment by uklimaschewski** [comment]
Thank you, you are welcome.
The scientific notation is not produced by EvaEx, it is a result of the `toString()` method of the `BigDecimal class`.
You can use the `toPlainString()` method on the BigDecimal result to avoid the scientific notation.

**Comment by Frietziek** [comment]
Thanks a lot men! Its work fine now :)
