### ISSUE TITLE
Default precision is 7 instead of 13 ?

### ISSUE THREAD

**Issue by sdiwu** [uklimaschewski/EvalEx#44]
I found out that the precision of BigDecimal result from `Expression.eval()` is 7 instead of 13 which is default in BigDecimal:
	
	   BigDecimal bd = new BigDecimal("1442503274032");
	   System.out.println(bd.precision());    // print 13
	
	   Expression expr = new Expression("1442503274032");
	   BigDecimal res = expr.eval();
	   System.out.println(res.precision());    // print 7

Is there a reason why use 7 instead of 13 ? 
I know the precision can be set but I prefer if it conforms to the default.

**Comment by squeek502** [comment]
[The precision of 7 comes from using `MathContext.DECIMAL32` by default](https://github.com/uklimaschewski/EvalEx/blob/master/src/com/udojava/evalex/Expression.java#L210). See http://docs.oracle.com/javase/7/docs/api/java/math/MathContext.html#DECIMAL32

As for *why* that's the default, I'm not sure.

**Comment by squeek502** [comment]
Looked into this a bit more. The 13 precision you are seeing in your default BigDecimal is not actually a default precision. It adapts to the number of digits.

Looking at the BigDecimal source code:

[precision field](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/math/BigDecimal.java#243):
> `    private volatile transient int precision = 0;`

[precision method]():

> ```
    /**
     * Returns the <i>precision</i> of this {@code BigDecimal}.  (The
     * precision is the number of digits in the unscaled value.)
     *
     * <p>The precision of a zero value is 1.
     *
     * @return the precision of this {@code BigDecimal}.
     * @since  1.5
     */
    public int precision() {
        int result = precision;
        if (result == 0) {
            result = digitLength();
            precision = result;
        }
        return result;
    }
```

If I'm correct, then this should be true:

```
   BigDecimal bd = new BigDecimal("123");
   System.out.println(bd.precision());    // print 3
```

And if that's true, then it looks like [MathContext.UNLIMITED](http://docs.oracle.com/javase/7/docs/api/java/math/MathContext.html#UNLIMITED) would be the 'correct' default.

**Comment by uklimaschewski** [comment]
Exactly, @squeek502. There is no default MathContext in Java, so I had to choose one specific. DECIMAL32 won the race. I think there was some reason after some tests, but I'm not sure.
Just read your second commen, @squeek502 and that may have been one reason.
Probably a separate constructor `Expression(String expression, MathContext context)` could give more flexibility.

**Comment by sdiwu** [comment]
Hi all, thanks for the clarification. I guess for now I will set the precision to 0 and rounding mode to HALF_UP to match the default behavior (UNLIMITED).
