### ISSUE TITLE
Support for implicit multiplication

### ISSUE THREAD

**Issue by FlashTek** [uklimaschewski/EvalEx#64]
Hello,
are there any plans to support implicit multiplications, so that `5SIN(2)` will be interpreted as `5*SIN(2)`? (Or is this even already possible and I am just unable to find this functionality?)

Edit: I tried to solve this issue by modifing the `shuntingYard` method by adding addition if-statements like this
    
    if (isNumber(token)) {
          if (previousToken != null && ")".equals(previousToken))
          {
               stack.push("×");
          }
         ...
    } else if (functions.containsKey(token.toUpperCase(Locale.ROOT))) {
         if (previousToken != null && isNumber(previousToken))
         {
                stack.push("×");
         }
     ....

This seems to work after a few test, but I am not completely sure about it. Are there any opinions?

**Comment by uklimaschewski** [comment]
I am not very happy with this kind of syntax, it has the potential to open a whole new can of worms.
E.g. What about `A5BSIN(2)` - is this a function named `A5BSIN` or an expression `A*5*SIN(2)` ?

**Comment by FlashTek** [comment]
Hm, that's a true problem. But are there any plans to support these multiplications? Because they are somehow very often used by users...
