### ISSUE TITLE
Some expressions not working

### ISSUE THREAD

**Issue by Dimalenus** [uklimaschewski/EvalEx#69]
The expression "3*-(2+2)" and "-(2+2)+8*5" not working. Please fix this.

**Comment by uklimaschewski** [comment]
The expression `3-(2+2)` is working and giving a result of -1.
The expression `-(2+2)+85` is invalid. The `-` is not supported as a prefix operator.

**Comment by Dimalenus** [comment]
I write 3*-(2+2) not understand why "*" not appeared, and by the that i i studied in mathematics a "-" before of a parentheses denies the result that is between he.

**Comment by Dimalenus** [comment]
i am making a calculator for android, and your class is really perfect for me, and by account of this bug, i that use expressionString.replace ("*-(", "*-1*("); what not is very nice.

**Comment by uklimaschewski** [comment]
I understand that and I'd like to have them, too, but unary operators are not supported at the moment, see issue #36.

**Comment by element111** [comment]
The expression 5+5 (105+5, 255+5, 75+5 etc.)giving a result of 1E+1. Why?

**Comment by squeek502** [comment]
@element111 use `toPlainString()`. See http://stackoverflow.com/questions/925232/why-does-java-bigdecimal-return-1e1

**Comment by element111** [comment]
@squeek502 Thanks a lot.
