### ISSUE TITLE
Scientific Notation Support

### ISSUE THREAD

**Issue by zurche** [uklimaschewski/EvalEx#75]
Hello, I have been trying to use the lib for large numbers and the result is shown in scientific notation, which is great. Anyway there's an issue when I try to use that result for a new expression, lets say:
2.551633e11*5

I get an exception: 
java.lang.RuntimeException: Unknown operator or function: e11

And I've checked through the github repository and I've found some unit tests for scientific notation, but I couldnt find this in the lib. Is this supported in future versions and not in 1.0?

Thanks in advance.

**Comment by uklimaschewski** [comment]
This feature was added in version 1.2, the actual version is 1.3.
Where do you get your binaries from?

**Comment by zurche** [comment]
Oh I see, I was using the version suggested in the readme file which was 1.0. I will update to 1.3. Thank you!
