### ISSUE TITLE
Support for more trigonometric functions

### ISSUE THREAD

**Issue by kingdom2011** [uklimaschewski/EvalEx#77]
currently it supports Sin, Cos, Tan. hyperbolic and also arc.
it would be nice if it could answer below functions:
Sec, Csc
Sech, Csch
Cot, aCot, Coth
aSinh, aCosh, aTanh

**Comment by squeek502** [comment]
Note that you can add custom functions to an expression, so you could add these functions yourself without needing them to be included by default. See [TestCustoms.java](https://github.com/uklimaschewski/EvalEx/blob/master/tests/com/udojava/evalex/TestCustoms.java#L26-L38) for an example.

**Comment by xLukasbx** [comment]
Can I get access to this repository? I would like make pull request with more trygonometric function.

**Comment by RobertZenz** [comment]
@xLukasbx You don't need access to this repository to do a pull request...that's the whole point of git. Fork it, work on your copy of the project and then make a pull request. [Here is a simple reference card](https://i.imgur.com/1lLtsgE.png) I made for this purpose.

**Comment by uklimaschewski** [comment]
@xLukasbx just like @RobertZenz said, go ahead and I will be happy to have a look at what you have done.

**Comment by xLukasbx** [comment]
@RobertZenz Thank you for prompt. I forgot about fork repository before make PR. I did PR with more trygonometric functions. Any comments are welcome.

**Comment by uklimaschewski** [comment]
Has been implemented in version 1.16
