### ISSUE TITLE
other function use

### ISSUE THREAD

**Issue by sebahattinkoc** [uklimaschewski/EvalEx#78]
hello;

my function

public int test(int a, int b, int c) {
    return a+b+c;;
}

can i use

Expression e = new Expression("2 * test(12,4,8)");

            e.addFunction(e.new Function("test", -1) {
                @Override
                public BigDecimal eval(List<BigDecimal> parameters) {
                    if (parameters.size() == 0) {
                        throw new Expression.ExpressionException("average requires at least one parameter");
                    }
                    BigDecimal avg = new BigDecimal(0);
                    for (BigDecimal parameter : parameters) {
                        avg = avg.add(parameter);
                    }
                    return avg.divide(new BigDecimal(parameters.size()));
                }
            });

            e.eval(); 

thank you, and thank you google translate :)

**Comment by squeek502** [comment]
```
public int test(int a, int b, int c) {
	return a+b+c;
}

Expression e = new Expression("2 * test(12,4,8)");
e.addFunction(e.new Function("test", 3) {
	@Override
	public BigDecimal eval(List<BigDecimal> parameters) {
		int result = test(parameters.get(0).intValue(), parameters.get(1).intValue(), parameters.get(2).intValue());
		return new BigDecimal(result);
	}
});
```

**Comment by sebahattinkoc** [comment]
Teşekkürler, thank you.
