### ISSUE TITLE
Functions use.

### ISSUE THREAD

**Issue by sebahattinkoc** [uklimaschewski/EvalEx#79]
hi;

//my functions;

public Double FICLC(String item, Integer param){
        return 1d; 
} 
public Double FGCLC(String item, String itemtwo, Integer param){
        return 1d; 
}
public Double FYCLC(String item){
        return 1d; 
}

new Expression("(FICLC("012844098501",1)>=1) && (FGCLC("A11","ABC",1)>1) && (FYCLC("A11")=1) ");

I have to watch how a road ?

Thank you.

**Comment by squeek502** [comment]
String literals are not supported currently. See https://github.com/uklimaschewski/EvalEx/issues/70
