### ISSUE TITLE
Mutability of Expression makes it non ideal for using the cached instance 

### ISSUE THREAD

**Issue by somasundaramsekar** [uklimaschewski/EvalEx#83]
```
public class Equation {

    private String expressionString;
    private Expression expression;

    public Equation(String expressionString) {
        hasLength(expressionString, "Invalid Expression %s specified");
        this.expressionString = expressionString;
        expression = new Expression(expressionString);
    }
}
```

the above equation instance has expression string and constructs Expression once and caches the equation, but since the Expression mutates the internal map, it becomes very cumbersome to evaluate the expression as the below 

(-327865.5593 + Yearly \* 7699.1161 + FQ1 \* 118965.3548 + FQ2 \* -19003.9418 -38640 + FQ3 \* 75560 + FQ4 \* -21700)/1000000

where we can expect only one fQ per execution, and while doing batch execution, the evaluation can quickly get cumbersome, 

what I basically want to do is 

```
public List<BigDecimal> eval(Map<TimeLineInQuarter.Quarters, Double> variables, Yearly y) {
              Arrays.stream(TimeLineInQuarter.Quarters.values()).forEach(
                Errors.rethrow().wrap(q -> {
                            expression.with("Yearly", new BigDecimal(y.quarterly(q)))
                                    .with(q.name(), new BigDecimal(variables.get(q)));
                        }
                )
        );

      //not intended to compile, Idea is I will be able to execute the equation for every quarter for a given year
        return collectedvalue;

    }
```

 Making the Expression immutable, I would be able to use the same Expression multiple times, but in the above case, I will end up constructing one expression per execution, though it may appear to be specific to my equation, I would stress that Immutable Expression would be ideal as construction of Expression as I see is costly

**Comment by squeek502** [comment]
I'm having trouble understanding exactly what you mean. Could you give a simpler example showing a simple expression, the current (incorrect) outcome, and your desired outcome?

**Comment by somasundaramsekar** [comment]
In my case I have to evaluate the expression 

> (-327865.5593 + Yearly * 7699.1161 + FQ1 * 118965.3548 + FQ2 * -19003.9418 -38640 + FQ3 * 75560 + FQ4 * -21700)/1000000

once for each quarter identified by FQ(X), which I intend to do with 

```
Arrays.stream(TimeLineInQuarter.Quarters.values()).forEach(
                Errors.rethrow().wrap(q -> {
                            expression.with("Yearly", new BigDecimal(y.quarterly(q)))
                                    .with(q.name(), new BigDecimal(variables.get(q)));
                        }
                )
        );
```

the problem here is after I do a .with() once the Expression instance used is mutated, so I cannot effectively use the same expression instance again, I have to create a new Expression instance for every iteration of the forEach above.

From the source code I could see new Expression is a heavy weight operation. If at all Expression.with() is immutable, returning me an new instance of Expression which is efficient as decided by you, will save us a lot of processing in cases like this where we want to construct the Expression once and reuse across multiple evaluations.

**Comment by squeek502** [comment]
Are you saying you want to be able to do, for example:

```
Expression expression = new Expression("FQ1 + FQ2");
expression.with("FQ1", new BigDecimal(1));
// 1 + 0 == 1
assertEquals("1", expression.eval().toPlainString());

expression.with("FQ2", new BigDecimal(1));
// 0 + 1 == 1
assertEquals("1", expression.eval().toPlainString());
```

?

If so, it seems like the easier solution would be to reset all variables to 0 before each iteration.

```java
public Expression resetVariables(Expression expression)
{
    List<String> usedVars = expression.getUsedVariables();
    for (String usedVar : usedVars)
    {
        expression.setVariable(usedVar, new BigDecimal(0));
    }
    return expression;
}
```

then you could do:

```java
Arrays.stream(TimeLineInQuarter.Quarters.values()).forEach(
                Errors.rethrow().wrap(q -> {
                            resetVariables(expression).with("Yearly", new BigDecimal(y.quarterly(q)))
                                    .with(q.name(), new BigDecimal(variables.get(q)));
                        }
                )
        );
```

**Comment by somasundaramsekar** [comment]
This seems like an workaround. But is there a cleaner API provided way for this, can it accepted as an enhancement request.

On Wed, Oct 26, 2016 at 11:30 PM, Ryan Liptak <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you saying you want to be able to do, for example:

Expression expression = new Expression("FQ1 + FQ2");
expression.with("FQ1", new BigDecimal(1));
// 1 + 0 == 1
assertEquals("1", expression.eval().toPlainString());

expression.with("FQ2", new BigDecimal(1));
// 0 + 1 == 1
assertEquals("1", expression.eval().toPlainString());


?

If so, it seems like the easier solution would be to reset all variables to 0 before each iteration.

public Expression resetVariables(Expression expression)
{
    List<String> usedVars = expression.getUsedVariables();
    for (String usedVar : usedVars)
    {
        expression.setVariable(usedVar, new BigDecimal(0));
    }
    return expression;
}

then you could do:

Arrays.stream(TimeLineInQuarter.Quarters.values()).forEach(
                Errors.rethrow().wrap(q -> {
                            resetVariables(expression).with("Yearly", new BigDecimal(y.quarterly(q)))
                                    .with(q.name(), new BigDecimal(variables.get(q)));
                        }
                )
        );
