### ISSUE TITLE
factorial operator

### ISSUE THREAD

**Issue by nietoperz809** [uklimaschewski/EvalEx#84]
insert the following in the operators list:

        ///////////////////////////////////////////////////
        addOperator(new Operator("!", 50, true)
        {
            BigDecimal fac(BigDecimal n, BigDecimal acc)
            {
                if (n.equals(BigDecimal.ONE))
                {
                    return acc;
                }
                BigDecimal lessOne = n.subtract(BigDecimal.ONE);
                return fac(lessOne, acc.multiply(lessOne, mc));
            }

            @Override
            public BigDecimal eval (BigDecimal v1, BigDecimal v2)
            {
                return fac (v1, v1);
            }
        });
        ///////////////////////////////////////////////////

... then replace every ! in the input string with !0 to fake a second op
now one can calculate 
3!^4 = 1296
3! = 6
8! = 40320
and so on ...

**Comment by squeek502** [comment]
Why not make it a function instead?

**Comment by nietoperz809** [comment]
for the same reason why + is not a function: x = add (a,b)
! is the usual mathematical notation. :)

**Comment by squeek502** [comment]
Right, but there's currently no support for unary operators (see #36), so making it a function would remove the need for the search and replace hack.

**Comment by nietoperz809** [comment]
it's not a hack, it's a nice solution. :)
inserting fake operands enables this software to deal with unary operators. i think it will work in aller other cases (like negation, increment, etc..)

**Comment by uklimaschewski** [comment]
I agree with Ryan, a general support for unary operators would be better.
Have a look at issue #36, user yoavst has published some code, which is a good starting point.
Would be happy to have this feature in EvalEx.
