### ISSUE TITLE
Number format exception when 

### ISSUE THREAD

**Issue by JosefHruska** [uklimaschewski/EvalEx#86]
I use this library (version 1.4.) to evaluate expression in calculator. 
It looks like this:

```
BigDecimal result = BigDecimal.ZERO
String expression = ""

public void onButtonPressed(button: String) {
expression += button // I use just these symbols: 0-9, . ,+, - , / ,*, 
eval()
}
private Boolean eval() {
        Boolean isValid = true
        try {
            result = new Expression(expression).eval()
        } catch (Expression.ExpressionException e) {
            result = BigDecimal.ZERO
            isValid = false
        } catch (EmptyStackException e) {
            // It throws exception sometimes, but we always get correct result.
        }
        return isValid
    }
```
As you can see I start with empty string. Whenever I press a button I add it to `expression` which is evaluated after that.  
I check expression for ExpressionException but I found out that if i wrote two decimal points in row (f.e. 4 + 1..6 or 76..6) app crash with NumberFormatException. Here is a log:

```
  java.lang.NumberFormatException: For input string: "9."
                      at java.lang.Long.parseLong(Long.java:443)
                      at java.lang.Long.parseLong(Long.java:485)
                      at java.math.BigDecimal.<init>(BigDecimal.java:344)
                      at java.math.BigDecimal.<init>(BigDecimal.java:444)
                      at com.udojava.evalex.Expression$43.eval(Expression.java:1250)
                      at com.udojava.evalex.Expression.eval(Expression.java:1255)
```

I guess that all similiar exception should be handled in library and replaced with ExpressionException, right?

**Comment by uklimaschewski** [comment]
I never thought of using EvalEx this way, but why not. I possibly would have added a `public boolean isValid()` method to the `Expression` class and check that method, before evaluating.
Using EvalEx in your way may produce alot of strange Exceptions, a single `isValid()` method could catch them in general (catch Throwable) and return false for all exceptions.
