### ISSUE TITLE
multiple of 10

### ISSUE THREAD

**Issue by kainjinez** [uklimaschewski/EvalEx#88]
When i calculate 10*2, 10*3, 10*4, it always show 2E+1, 3E+1, 4E+1.
How to make it become 20, 30, 40?

**Comment by uklimaschewski** [comment]
You are probably using `BigDecimal.toString()` to print the result, it uses scientific notation. Use `BigDecimal.toPlainString()` instead. See issue #43.

**Comment by kainjinez** [comment]
Thank alot. It's work. Sorry I didn't know any keyword to find #43 .
