### ISSUE TITLE
Operator precedence

### ISSUE THREAD

**Issue by vipirain** [uklimaschewski/EvalEx#93]
Hi,

Thank you very much for maintaining EvalEX!
I would like to know the operator precedence.
I'm not sure if the table listing the operators also implicitly defines the precedence.
I would expect the following: 
`+ - * / % ^`

Is this correct?
Best regards

**Comment by squeek502** [comment]
Yes, you can see the operator precedence here: https://github.com/uklimaschewski/EvalEx/blob/master/src/com/udojava/evalex/Expression.java#L747-L872

(precedence is the second constructor argument)
