### ISSUE TITLE
If doesn't support Strings

### ISSUE THREAD

**Issue by marcfasel** [uklimaschewski/EvalEx#94]
We are using EvalEx in our application to provide Excel-like formulas. So far it is working great, but our if conditions may operate on Strings, e.g. IF("this"!="that",42,666) or even IF("this"="that","foo", "bar").

Is this something that could be supported? If not and it is this functionality you would want to have in this library we want to contribute it ...

Cheers

Marc

**Comment by squeek502** [comment]
Related: https://github.com/uklimaschewski/EvalEx/issues/70

**Comment by uklimaschewski** [comment]
Was implemented by @evanpratama with #106
