### ISSUE TITLE
I made the parser understand hex, octal an binary numbers

### ISSUE THREAD

**Issue by nietoperz809** [uklimaschewski/EvalEx#95]
The isNumber function begins like this

private boolean isNumber(String st)
 {
    if (st.startsWith("x")||st.startsWith("b")||st.startsWith("o"))
       return true;
  .....

and at line 1147 in the shuntingYard funtion I inserted the following ....

		if (isNumber(token))   // <--- // your code 
		{
		    if (token.startsWith("x"))
                       outputQueue.add(""+Integer.parseInt(token.substring(1), 16));
                    else if (token.startsWith("b"))
                       outputQueue.add(""+Integer.parseInt(token.substring(1), 2));
                    else if (token.startsWith("o"))
                       outputQueue.add(""+Integer.parseInt(token.substring(1), 8));
                    else  // <--- // your code
                       outputQueue.add(token);
                .....   

a simple test works

    @Test
    public void testPit1()
    {
        Expression e = new Expression("b11+11+x11+o11");
        Expression f = new Expression("3+11+17+9");
        assertEquals (e.eval(), f.eval());
        System.out.println(e.eval());
        System.out.println(f.eval());
    }

**Comment by nietoperz809** [comment]
Yes, this way it's only a quick hack. I need it for my command line tool, a calculator for programmers. 
they usually don't need hex numbers bigger than 2^64 or even floats in binary (that have a fractional part.) :)

Btw, in my first attempt I used 0x and 0b as prefix, but the parser sees the 0-character as the operand "Zero". Therefore it tokenizes e.g. 0xabcd into 0 and xabcd. 
I help him, so I leave out the 0. 

Btw2: It seems problematic (in matters of extending the parser) that it relies on whitespace as deliminiter. This breaks the well-proven principle of "greedy" token parsing. 
Nevertheless, your parser works great for me. Good job! 👍

**Comment by nietoperz809** [comment]
I replaced the hex/oct/bin input with something like this
`                    BigInteger bd = new BigInteger (token.substring(1), 16);
                    outputQueue.add(bd.toString(10));
`
And the output:
`                   BigDecimal ret = e.eval();
                    BigInteger big = ret.toBigInteger();
                    System.out.print(" Octal:" + big.toString(8));  // 8 for octal string
 `
Then I removed the MathContext stuff. Otherwise, there were weird rounding effects in very large numbers.

The parser can now handle numbers of arbitrary size in hex, dec, bin, oct. :)

**Comment by uklimaschewski** [comment]
If you want this, then please submit a PR. Have a look at https://github.com/uklimaschewski/EvalEx/commit/c5dcb9e5f44e0e1639460a80dbccc76bdbe5c6e1 which looks like an implementation based on the new tokenizer by @revbingo.
It has been removed by him, but you may want to start from there.

**Comment by revbingo** [comment]
For the record I reverted because I pushed on the wrong branch and didn't want to pollute the original PR, but I will resubmit a separate PR for that code

**Comment by uklimaschewski** [comment]
Perfect, thanks!
